[package]
name = "sa-skills"
version.workspace = true
edition.workspace = true

[dependencies]
sa-domain = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
parking_lot = { workspace = true }
